### ISSUE TITLE
构建 YOLOV6 的 TensorRT 文件错误  build YOLOV6 TensorRT file error

### ISSUE THREAD

**Issue by linzhilin125** [Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2#10]
PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2> python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end

Traceback (most recent call last):
  File "D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2\tools\export.py", line 7, in <module>
    import tensorrt as trt
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 93, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', '', '', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files\\Bandizip\\', 'C:\\Program Files\\dotnet\\', 'E:\\Git\\cmd', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.2.0\\', 'E:\\python\\Scripts\\', 'E:\\python\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\', 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\', 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps', 'E:\\Microsoft VS Code\\bin', 'C:\\Program Files\\NVIDIA\\CUDNN\\v8.x\\bin', 'C:\\Program Files\\NVIDIA\\TensorRT-8.4.2.4\\lib', 'C:\\Program Files\\NVIDIA\\TensorRT-8.4.2.4\\bin', '']

PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2>
PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2>
PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2>
PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2>

版本 version

PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2> python -V
Python 3.10.4

PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2> pip -V
pip 22.3.1 from E:\python\lib\site-packages\pip (python 3.10)

PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2> trtexec.exe -h
PS D:\euro_track_simulate\Self-driving-Truck-in-Euro-Truck-Simulator2>

怎么解决这个问题？How to solve the problem？

**Comment by Yutong-gannis** [comment]
@linzhilin125 
`FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?`把CUDA目录下cublas64这个文件后面改成10就行了

**Comment by linzhilin125** [comment]
> @linzhilin125 `FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?`把CUDA目录下cublas64这个文件后面改成10就行了

好的，谢谢
