### ISSUE TITLE
无法正常转向的问题

### ISSUE THREAD

**Issue by zlz-star** [Yutong-gannis/Self-driving-Truck-in-Euro-Truck-Simulator2#8]
问题描述：
- 进入游戏后，可以前进后退停车，但无法转向
- 初始方向盘若不为正，则会立刻摆正
- 键盘控制仍然有效（笔记本键盘，带小键盘）

已经确定无误的：
- vjoy虚拟手柄软件已经安装
- 模组Google Maps Navigation Night Version和SISL's Route Adviser已经启用
- 控制改为键盘+vjoy Device
- 键盘键位设为默认
- 程序正常识别
- steam控制器设置中，所有控制器支持均打开

**Comment by Yutong-gannis** [comment]
@zlz-star 打开导航了吗，导航地图要切换到最大的

**Comment by zlz-star** [comment]
试过了，仍然不行

**Comment by Yutong-gannis** [comment]
好像要在vjoy里添加设备

**Comment by zlz-star** [comment]
steer angle要么为-6左右，要么为0，能识别车道线，但很少见地图上拟合出轨迹。

**Comment by Yutong-gannis** [comment]
@zlz-star 移到屏幕左上角，自己再根据效果微调一下

**Comment by ywjno** [comment]
貌似需要保证切到最大化的导航地图在监视的窗口里保持正中才行，游戏里面按F1暂停游戏然后调整游戏窗口所在位置试试

普通道路的话自动驾驶没问题，复杂道路还得自己来

**Comment by zlz-star** [comment]
貌似是生成engine文件出了问题，原来的模型在计算steer angle出了bug。重启电脑后改了改环境，就能跑了，但是转向不稳定，很容易翻车。
请问模型的精度是哪个，是int32、int64还是浮点类型？

**Comment by zlz-star** [comment]
貌似是生成engine文件出了问题，原来的模型在计算steer angle出了bug。重启电脑后改了改环境，就能跑了，但是转向不稳定，很容易翻车。
请问模型的精度是哪个，是int32、int64还是浮点类型？

**Comment by ywjno** [comment]
在生成 yolo engine文件的那个命令里面加个参数试试`python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end -p fp32`

`-p` 默认是fp16，支持 fp32、fp16、int8

**Comment by ywjno** [comment]
然后看转换 engine 的 log 输出内容，要是发现有 `Building fp16 Engine in D:\Self-driving-Truck-in-Euro-Truck-Simulator2\engines\yolov6s_bdd_60.engine
FP16 is not supported natively on this platform/device` 类似这样的提示消息说不支持fp16的继续在命令行里面加参数 `python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end --conf_thres 0.6 -p fp32`

`-p` 参数接受 fp32、fp16、int8 这三个中其中一个，默认是 fp16

**Comment by zlz-star** [comment]
在输入构建 CLRNet 的 TensorRT 文件的命令后出现了`onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32 `
据说是pytorch和onnx版本不兼容，但我不知道哪个版本的onnx是适合于1.13.1的torch的

**Comment by ywjno** [comment]
那这个就不清楚了。。。只能一个个版本试了

**Comment by ywjno** [comment]
要么把torch的版本变成 1.9.1 试试

**Comment by ywjno** [comment]
貌似跟torch没有关系，这个问题感觉更像是生成的 onnx 文件的问题（比如用的显卡支持int64的类型但是10系显卡只支持到int32）

**Comment by zlz-star** [comment]
哦，我用的1060的显卡
我试了用`onnx-simplifier`简化模型，确实steer angle正常了，但是转向仍然不稳定

**Comment by zlz-star** [comment]
转向的参数是main.py中的`horizontal_pid = PID(0.02, 0.0005, 0.01)  # 初始化横向PID控制算法`吗？还与其他有关吗？
我试着改了三个参数，有一定作用，但也没调到稳定的结果

**Comment by zlz-star** [comment]
Cruise函数里pid被注释掉了，横向用的pure pursuit

**Comment by Yutong-gannis** [comment]
@zlz-star 把转向灵敏度调低一点试试

**Comment by Yutong-gannis** [comment]
分辨率设为1360x768，之前一直没注意写错了

**Comment by HLeonHong** [comment]
> 哦，我用的1060的显卡 我试了用`onnx-simplifier`简化模型，确实steer angle正常了，但是转向仍然不稳定

我的是1050ti
也有这个情况出现
onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32 

请问是一定要简化 模型不?

**Comment by zlz-star** [comment]
我新测试了下，发现几个问题：
1.笔记本1650显卡性能不足，运行时infer time一般在0.33s左右，超过了设定的决策间隔时间0.2s
2.转向灵敏度理论上应该高一些，但是由于控制间隔较长，所以不能太高
3.非线性转向可以一定程度上缓解左右摇摆的问题，但是一般情况下转向迟滞
4.车身长度好像也有一定影响

**Comment by zlz-star** [comment]
@HLeonHong 不建议尝试了，简化后的模型尚且跑起来较慢，不简化可能更慢。不过我没试过，我不简化会报错。
该换显卡了，哎

**Comment by HLeonHong** [comment]
> @HLeonHong 不建议尝试了，简化后的模型尚且跑起来较慢，不简化可能更慢。不过我没试过，我不简化会报错。 该换显卡了，哎

哎, 这是略难过的事
看来还得有个台式机才好

**Comment by Yutong-gannis** [comment]
@HLeonHong 现在还没太用到车道线，但是是推理时间最长的部分，可以把主函数里车道线检测的部分给注释掉，赋值None给bevlane，应该也能跑

**Comment by HLeonHong** [comment]
> @HLeonHong 现在还没太用到车道线，但是是推理时间最长的部分，可以把主函数里车道线检测的部分给注释掉，赋值None给bevlane，应该也能跑

我知识储备不太够（sad）. 还望作者多指导

**Comment by zlz-star** [comment]
@Yutong-gannis 能具体说下车道线检测是哪几行吗？

**Comment by zlz-star** [comment]
我改了改车速的控制，现在能适应绝大多数高速路了。这个效果已经很满意了。
这个问题结束了吧

**Comment by HLeonHong** [comment]
> 我改了改车速的控制，现在能适应绝大多数高速路了。这个效果已经很满意了。 这个问题结束了吧

我也太羡慕了
可否 + 个好友, 交流学习下?

**Comment by zlz-star** [comment]
@HLeonHong 有问题的话可以发邮件到 `boer_s_horseshoes@163.com`，我会尽可能回复

**Comment by HLeonHong** [comment]
> 我改了改车速的控制，现在能适应绝大多数高速路了。这个效果已经很满意了。 这个问题结束了吧

请问如何修改车速的, 是在main.py里修改吗

**Comment by Yutong-gannis** [comment]
@HLeonHong main.py里直接修改speed_limit可以直接限速
